# Generated by Django 6.0 on 2025-12-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('KG', 'KG'), ('TFG', 'TFG'), ('Winvested', 'Winvested'), ('Mirka', 'Mirka'), ('Sparco', 'Sparco'), ('Others', 'Others')], max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('gcbl_no', models.CharField(max_length=50)),
                ('main_applicant', models.CharField(max_length=100)),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('fm', models.CharField(max_length=100)),
                ('initial_payment', models.BooleanField(default=False)),
                ('local_agent', models.CharField(max_length=100)),
                ('cbi_submission_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Passport Issued', 'Passport Issued'), ('Denied', 'Denied')], default='Pending', max_length=50)),
            ],
        ),
    ]
