# Generated by Django 6.0 on 2025-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status_notes',
        ),
        migrations.AddField(
            model_name='client',
            name='investment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
