# Generated by Django 6.0 on 2025-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_channel_name_remove_client_fm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
