# Generated by Django 6.0 on 2025-12-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_fm_alter_client_status'),
    ]

    operations = [
    ]
