# Generated by Django 6.0 on 2025-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20251230_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('KG', 'KG'), ('TFG', 'TFG'), ('Winvested', 'Winvested'), ('Mirka', 'Mirka'), ('Sparco', 'Sparco'), ('Roc Citizenship DMCC', 'Roc Citizenship DMCC'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='fm',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='gcbl_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='local_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_applicant',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Passport Issued', 'Passport Issued'), ('Denied', 'Denied')], max_length=100),
        ),
    ]
