# Generated by Django 6.0 on 2025-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_status_notes_alter_client_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Passport Issued', 'Passport Issued'), ('Denied', 'Denied')], max_length=100),
        ),
    ]
