# Generated by Django 6.0 on 2025-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='other_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
