# Generated by Django 6.0 on 2025-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_company_alter_client_fm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('Roc', 'Roc'), ('Citizenship DMCC', 'Citizenship DMCC'), ('Greeth Brookes', 'Greeth Brookes'), ('Consultants', 'Consultants'), ('Passport Gate', 'Passport Gate'), ('Citizenship Invest DMCC', 'Citizenship Invest DMCC'), ('KG', 'KG'), ('TFG', 'TFG'), ('Mirka', 'Mirka'), ('Sparco', 'Sparco'), ('Winvested', 'Winvested'), ('Others', 'Others')], default='Roc', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_company',
            field=models.CharField(blank=True, help_text="Fill only if 'Others' is selected as company", max_length=255, null=True),
        ),
    ]
