# Generated by Django 6.0 on 2025-12-30 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_company_alter_client_other_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('Roc', 'Roc'), ('Citizenship DMCC', 'Citizenship DMCC'), ('Greeth Brookes', 'Greeth Brookes'), ('Consultants', 'Consultants'), ('Passport Gate', 'Passport Gate'), ('Citizenship Invest DMCC', 'Citizenship Invest DMCC'), ('KG', 'KG'), ('TFG', 'TFG'), ('Mirka', 'Mirka'), ('Sparco', 'Sparco'), ('Winvested', 'Winvested'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Current', 'Current'), ('Approved', 'Approved'), ('Issued', 'Issued'), ('Denied', 'Denied')], default='Current', max_length=20),
        ),
    ]
