# Generated by Django 6.0 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_created_at_client_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('Roc Citizenship DMCC', 'Roc Citizenship DMCC'), ('Greeth Brookes', 'Greeth Brookes'), ('Consultants', 'Consultants'), ('Passport Gate', 'Passport Gate'), ('Citizenship Invest DMCC', 'Citizenship Invest DMCC'), ('KG', 'KG'), ('TFG', 'TFG'), ('Mirka', 'Mirka'), ('Sparco', 'Sparco'), ('Winvested', 'Winvested'), ('Others', 'Others')], max_length=255),
        ),
    ]
