# Generated by Django 6.0 on 2025-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_client_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='initial_payment',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='investment',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
