# Generated by Django 6.0 on 2025-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_initial_payment_alter_client_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='initial_payment',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='investment',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, default='Current', max_length=50, null=True),
        ),
    ]
